### ISSUE TITLE
Nice Job!

### ISSUE THREAD

**Issue by albertbahia** [stvbuller/ClickYouFriends#1]
Nice job with the homework.  One suggestion would be to implement some styling to the images to notify the user.

Things to keep note:
- Make sure to watch your indents with your `<script></script>` tags on **_lines 132-133_** (https://github.com/stvbuller/ClickYouFriends/blob/master/index.html#L132-L133).
- For best practice, I would move your code in **_lines 7-9_** of your **_countImages.js_** (https://github.com/stvbuller/ClickYouFriends/blob/master/jscripts/countImages.js#L7-L9) to the bottom after you've defined all your variables and functions.  
- Having all your functions and variables defined at the top before doing anything makes for better code readability as well promoting good structure.

**Comment by stbuller** [comment]
Added styling to the images to notify the user, and corrected code issues
